-- Q1. Top Revenue-Generating Locations & Average Customer Age

SELECT location, 
       SUM(purchase_amount) AS total_revenue, 
       ROUND(AVG(age), 1) AS avg_customer_age
FROM customer
GROUP BY location
ORDER BY total_revenue DESC
LIMIT 5;

-- Q2. Payment Method Preferences and Total Revenue
SELECT payment_method, 
       COUNT(customer_id) AS total_transactions, 
       ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY payment_method
ORDER BY total_revenue DESC;

-- Q3. Seasonal Category Performance.
SELECT season, 
       category, 
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY season, category
ORDER BY season, total_revenue DESC;

-- Q4. Discount Impact on Customer Review Ratings
SELECT discount_applied, 
       ROUND(AVG(review_rating), 2) AS avg_review_rating, 
       COUNT(customer_id) AS total_purchases
FROM customer
GROUP BY discount_applied;




-- Q5. What is the total revenue generated by male vs. female customers?[cite: 1]
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

-- Q6. Do subscribed customers spend more? Compare average spend and total revenue.[cite: 1]
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount), 2) AS avg_spend,
       ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;

-- Q7. Segment customers into New, Returning, and Loyal based on previous purchases.[cite: 1]
WITH customer_type AS (
    SELECT customer_id, previous_purchases,
    CASE 
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment
    FROM customer
)
SELECT customer_segment, COUNT(*) AS "Number of Customers" 
FROM customer_type 
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category?[cite: 1]
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;
